services:
  discovery1:
    build: .
    container_name: discovery1
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery2:8762/eureka
    ports:
      - "8761:8761"
    networks:
      - dist-sys-ms-network

  discovery2:
    build: .
    container_name: discovery2
    environment:
      - SERVER_PORT=8762
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery1:8761/eureka
    ports:
      - "8762:8762"
    networks:
      - dist-sys-ms-network

networks:
  dist-sys-ms-network:
    external: true
