spring:
    application:
        name: discovery
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config
    config:
        import: "optional:configserver:"

eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        prefer-ip-address: true
