spring:
    application:
        name: discovery
    cloud:
        config:
            discovery:
                enabled: true
                service-id: config
            request-connected-timeout: 5000
            request-read-timeout: 5000
            fail-fast: true
            retry:
                max-attempts: 10
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1
    config:
        import: "optional:configserver:"

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_SERVICE_URL}
    instance:
        hostname: ${EUREKA_HOSTNAME}
        prefer-ip-address: false
